'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.0.3705.288
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Data
Imports System.Runtime.Serialization
Imports System.Xml


<Serializable(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Diagnostics.DebuggerStepThrough(),  _
 System.ComponentModel.ToolboxItem(true)>  _
Public Class myresdata
    Inherits DataSet
    
    Private tableRespdata As RespdataDataTable
    
    Public Sub New()
        MyBase.New
        Me.InitClass
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    Protected Sub New(ByVal info As SerializationInfo, ByVal context As StreamingContext)
        MyBase.New
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(System.String)),String)
        If (Not (strSchema) Is Nothing) Then
            Dim ds As DataSet = New DataSet
            ds.ReadXmlSchema(New XmlTextReader(New System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("Respdata")) Is Nothing) Then
                Me.Tables.Add(New RespdataDataTable(ds.Tables("Respdata")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.InitClass
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <System.ComponentModel.Browsable(false),  _
     System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property Respdata As RespdataDataTable
        Get
            Return Me.tableRespdata
        End Get
    End Property
    
    Public Overrides Function Clone() As DataSet
        Dim cln As myresdata = CType(MyBase.Clone,myresdata)
        cln.InitVars
        Return cln
    End Function
    
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As XmlReader)
        Me.Reset
        Dim ds As DataSet = New DataSet
        ds.ReadXml(reader)
        If (Not (ds.Tables("Respdata")) Is Nothing) Then
            Me.Tables.Add(New RespdataDataTable(ds.Tables("Respdata")))
        End If
        Me.DataSetName = ds.DataSetName
        Me.Prefix = ds.Prefix
        Me.Namespace = ds.Namespace
        Me.Locale = ds.Locale
        Me.CaseSensitive = ds.CaseSensitive
        Me.EnforceConstraints = ds.EnforceConstraints
        Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
        Me.InitVars
    End Sub
    
    Protected Overrides Function GetSchemaSerializable() As System.Xml.Schema.XmlSchema
        Dim stream As System.IO.MemoryStream = New System.IO.MemoryStream
        Me.WriteXmlSchema(New XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return System.Xml.Schema.XmlSchema.Read(New XmlTextReader(stream), Nothing)
    End Function
    
    Friend Sub InitVars()
        Me.tableRespdata = CType(Me.Tables("Respdata"),RespdataDataTable)
        If (Not (Me.tableRespdata) Is Nothing) Then
            Me.tableRespdata.InitVars
        End If
    End Sub
    
    Private Sub InitClass()
        Me.DataSetName = "myresdata"
        Me.Prefix = ""
        Me.Namespace = "http://www.tempuri.org/myresdata.xsd"
        Me.Locale = New System.Globalization.CultureInfo("en-US")
        Me.CaseSensitive = false
        Me.EnforceConstraints = true
        Me.tableRespdata = New RespdataDataTable
        Me.Tables.Add(Me.tableRespdata)
    End Sub
    
    Private Function ShouldSerializeRespdata() As Boolean
        Return false
    End Function
    
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    Public Delegate Sub RespdataRowChangeEventHandler(ByVal sender As Object, ByVal e As RespdataRowChangeEvent)
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class RespdataDataTable
        Inherits DataTable
        Implements System.Collections.IEnumerable
        
        Private columnCallID As DataColumn
        
        Private columnDcollect As DataColumn
        
        Private columnid As DataColumn
        
        Private columnQID As DataColumn
        
        Friend Sub New()
            MyBase.New("Respdata")
            Me.InitClass
        End Sub
        
        Friend Sub New(ByVal table As DataTable)
            MyBase.New(table.TableName)
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
            Me.DisplayExpression = table.DisplayExpression
        End Sub
        
        <System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        Friend ReadOnly Property CallIDColumn As DataColumn
            Get
                Return Me.columnCallID
            End Get
        End Property
        
        Friend ReadOnly Property DcollectColumn As DataColumn
            Get
                Return Me.columnDcollect
            End Get
        End Property
        
        Friend ReadOnly Property idColumn As DataColumn
            Get
                Return Me.columnid
            End Get
        End Property
        
        Friend ReadOnly Property QIDColumn As DataColumn
            Get
                Return Me.columnQID
            End Get
        End Property
        
        Public Default ReadOnly Property Item(ByVal index As Integer) As RespdataRow
            Get
                Return CType(Me.Rows(index),RespdataRow)
            End Get
        End Property
        
        Public Event RespdataRowChanged As RespdataRowChangeEventHandler
        
        Public Event RespdataRowChanging As RespdataRowChangeEventHandler
        
        Public Event RespdataRowDeleted As RespdataRowChangeEventHandler
        
        Public Event RespdataRowDeleting As RespdataRowChangeEventHandler
        
        Public Overloads Sub AddRespdataRow(ByVal row As RespdataRow)
            Me.Rows.Add(row)
        End Sub
        
        Public Overloads Function AddRespdataRow(ByVal CallID As String, ByVal Dcollect As String, ByVal QID As String) As RespdataRow
            Dim rowRespdataRow As RespdataRow = CType(Me.NewRow,RespdataRow)
            rowRespdataRow.ItemArray = New Object() {CallID, Dcollect, Nothing, QID}
            Me.Rows.Add(rowRespdataRow)
            Return rowRespdataRow
        End Function
        
        Public Function FindByid(ByVal id As Integer) As RespdataRow
            Return CType(Me.Rows.Find(New Object() {id}),RespdataRow)
        End Function
        
        Public Function GetEnumerator() As System.Collections.IEnumerator Implements System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        Public Overrides Function Clone() As DataTable
            Dim cln As RespdataDataTable = CType(MyBase.Clone,RespdataDataTable)
            cln.InitVars
            Return cln
        End Function
        
        Protected Overrides Function CreateInstance() As DataTable
            Return New RespdataDataTable
        End Function
        
        Friend Sub InitVars()
            Me.columnCallID = Me.Columns("CallID")
            Me.columnDcollect = Me.Columns("Dcollect")
            Me.columnid = Me.Columns("id")
            Me.columnQID = Me.Columns("QID")
        End Sub
        
        Private Sub InitClass()
            Me.columnCallID = New DataColumn("CallID", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnCallID)
            Me.columnDcollect = New DataColumn("Dcollect", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnDcollect)
            Me.columnid = New DataColumn("id", GetType(System.Int32), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnid)
            Me.columnQID = New DataColumn("QID", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnQID)
            Me.Constraints.Add(New UniqueConstraint("Constraint1", New DataColumn() {Me.columnid}, true))
            Me.columnid.AutoIncrement = true
            Me.columnid.AllowDBNull = false
            Me.columnid.Unique = true
        End Sub
        
        Public Function NewRespdataRow() As RespdataRow
            Return CType(Me.NewRow,RespdataRow)
        End Function
        
        Protected Overrides Function NewRowFromBuilder(ByVal builder As DataRowBuilder) As DataRow
            Return New RespdataRow(builder)
        End Function
        
        Protected Overrides Function GetRowType() As System.Type
            Return GetType(RespdataRow)
        End Function
        
        Protected Overrides Sub OnRowChanged(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.RespdataRowChangedEvent) Is Nothing) Then
                RaiseEvent RespdataRowChanged(Me, New RespdataRowChangeEvent(CType(e.Row,RespdataRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowChanging(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.RespdataRowChangingEvent) Is Nothing) Then
                RaiseEvent RespdataRowChanging(Me, New RespdataRowChangeEvent(CType(e.Row,RespdataRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleted(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.RespdataRowDeletedEvent) Is Nothing) Then
                RaiseEvent RespdataRowDeleted(Me, New RespdataRowChangeEvent(CType(e.Row,RespdataRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleting(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.RespdataRowDeletingEvent) Is Nothing) Then
                RaiseEvent RespdataRowDeleting(Me, New RespdataRowChangeEvent(CType(e.Row,RespdataRow), e.Action))
            End If
        End Sub
        
        Public Sub RemoveRespdataRow(ByVal row As RespdataRow)
            Me.Rows.Remove(row)
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class RespdataRow
        Inherits DataRow
        
        Private tableRespdata As RespdataDataTable
        
        Friend Sub New(ByVal rb As DataRowBuilder)
            MyBase.New(rb)
            Me.tableRespdata = CType(Me.Table,RespdataDataTable)
        End Sub
        
        Public Property CallID As String
            Get
                Try 
                    Return CType(Me(Me.tableRespdata.CallIDColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableRespdata.CallIDColumn) = value
            End Set
        End Property
        
        Public Property Dcollect As String
            Get
                Try 
                    Return CType(Me(Me.tableRespdata.DcollectColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableRespdata.DcollectColumn) = value
            End Set
        End Property
        
        Public Property id As Integer
            Get
                Return CType(Me(Me.tableRespdata.idColumn),Integer)
            End Get
            Set
                Me(Me.tableRespdata.idColumn) = value
            End Set
        End Property
        
        Public Property QID As String
            Get
                Try 
                    Return CType(Me(Me.tableRespdata.QIDColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableRespdata.QIDColumn) = value
            End Set
        End Property
        
        Public Function IsCallIDNull() As Boolean
            Return Me.IsNull(Me.tableRespdata.CallIDColumn)
        End Function
        
        Public Sub SetCallIDNull()
            Me(Me.tableRespdata.CallIDColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsDcollectNull() As Boolean
            Return Me.IsNull(Me.tableRespdata.DcollectColumn)
        End Function
        
        Public Sub SetDcollectNull()
            Me(Me.tableRespdata.DcollectColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsQIDNull() As Boolean
            Return Me.IsNull(Me.tableRespdata.QIDColumn)
        End Function
        
        Public Sub SetQIDNull()
            Me(Me.tableRespdata.QIDColumn) = System.Convert.DBNull
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class RespdataRowChangeEvent
        Inherits EventArgs
        
        Private eventRow As RespdataRow
        
        Private eventAction As DataRowAction
        
        Public Sub New(ByVal row As RespdataRow, ByVal action As DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        Public ReadOnly Property Row As RespdataRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        Public ReadOnly Property Action As DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
